### ISSUE TITLE
prevLogIndex in appendEntries

### ISSUE THREAD

**Issue by cphillips83** [ongardie/raftscope#13]
I can only find one reference to `prevLogIndex` in the raft js code, the rest of the code is accessing `prevIndex`. The PDF explaining AppendEntries has a `prevLogIndex` that sounds like `prevIndex` used through out the js code. I'm assuming `prevIndex` in the raft js code is actually `prevLogIndex` from the PDF and that the reference here to `prevLogIndex` should be renamed to `prevIndex` or all `prevIndex` should be renamed to `prevLogIndex`.

https://github.com/ongardie/raftscope/blob/a581e3dc24f7ab5954389aa00a9dc8a55b56f2fa/raft.js#L194

**Comment by ongardie** [comment]
Thanks, @cphillips83. You're right, that should be `prevIndex`. I don't think it'll make much difference though, since if prevIndex is 0, 
```
request.prevIndex <= server.log.length &&
logTerm(server.log, request.prevIndex) == request.prevTerm
```
will be:
```
0 <= server.log.length &&
0 == 0
```
which will always evaluate to true.
